import { Button, GridBox, LineEdit } from "std-widgets.slint";

component AutoclickUI {
    callback start();

    Button {
        text: "autoclick";

        clicked => {
            root.start();
        }
    }
}

export component MainWindow inherits Window {
    // icon: @image-url("icons/design.svg");
    title: @tr("AutoClick");

    callback start();

    width: 326px;
    height: 326px;

    AutoclickUI {
        start() => { root.start() }
    }
}
